/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

/**
 *
 * @author Dae
 */
public class frm extends javax.swing.JPanel {

    /**
     * Creates new form FrmCategorias
     */
    public frm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
private void btnRegistrarActionPerformed(
            java.awt.event.ActionEvent evt) {

        Categoria c
                = new Categoria();

        c.setCodigo(
                Integer.parseInt(
                        txtCodigo.getText()));

        c.setNombre(
                txtNombre.getText());

        sistema.registrarCategoria(c);
    }

    private void btnBuscarActionPerformed(
            java.awt.event.ActionEvent evt) {

        int codigo
                = Integer.parseInt(
                        txtCodigo.getText());

        Categoria c
                = sistema.buscarCategoria(codigo);

        if (c != null) {

            txtNombre.setText(
                    c.getNombre());

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
